### ISSUE TITLE
no builds triggered on master

### ISSUE THREAD

**Issue by Anthchirp** [conda-forge/pathlib2-feedstock#11]
https://github.com/conda-forge/pathlib2-feedstock/commits/master

There are a few green ticks in branches, but no builds running off master?

I don't know how dead Python 2.7 is in conda-forge but just thought I'd highlight that.

**Comment by beckermr** [comment]
If this is python 2.7 only, then indeed it won't. We should archive it if that is ok with @conda-forge/pathlib2

**Comment by Anthchirp** [comment]
Thanks!

While it does hold up the referenced PR, that's not really a blocker. (upstream has dropped this dependency in Feb 2019, they just haven't gotten around to making a release yet)

**Comment by Anthchirp** [comment]
good call on retriggering the master build first.

Looking at the Python 3.9 migration not-solveable log pathlib2 does show up in 2 packages.

**Comment by beckermr** [comment]
I think we are good to close this?
